import type { AppSettings } from '../types';

// The application's default settings. Cloned on load; also the target of the
// "Reset to defaults" action. Deep-cloneable plain data.
export function defaultSettings(): AppSettings {
  return {
    source: 'shape',
    shape: {
      kind: 'sphere',
      cube: {
        width: 2,
        height: 2,
        depth: 2,
        filled: false,
        edgeConcentration: 0.35,
        cornerRadius: 0.05,
      },
      sphere: {
        radius: 1.4,
        filled: false,
        hemisphere: false,
        latitudeCorrection: true,
      },
      helix: {
        radius: 1,
        height: 3,
        turns: 5,
        pitch: 1,
        strandThickness: 0.08,
        doubleHelix: true,
      },
      torus: {
        majorRadius: 1.2,
        minorRadius: 0.45,
        tubeThickness: 1,
        filled: false,
      },
      knot: {
        p: 2,
        q: 3,
        majorRadius: 1.1,
        tubeRadius: 0.35,
        twist: 0,
        thickness: 0.12,
      },
      lorenz: {
        sigma: 10,
        rho: 28,
        beta: 8 / 3,
        step: 0.006,
        scale: 0.055,
        jitter: 0.03,
      },
    },
    image: {
      sampleResolution: 320,
      alphaThreshold: 0.5,
      brightnessThreshold: 0.05,
      invertMask: false,
      fit: 'fit',
      useImageColor: true,
      solidColor: '#4f9dff',
      saturation: 1,
      contrast: 1,
      brightness: 1,
      depthMode: 'luminance',
      depthAmount: 0.6,
      depthDirection: 1,
      depthCurve: 1,
      edgeEmphasis: 0,
      noiseDepth: 0,
      scale: 1,
      rotation: 0,
      flipH: false,
      flipV: false,
      bgRemoval: 0,
      layers: 6,
    },
    text: {
      content: 'PARTICLE\nSTUDIO',
      fontFamily: 'Inter, Arial, sans-serif',
      fontWeight: 800,
      fontSizePx: 200,
      letterSpacing: 0,
      lineHeight: 1.05,
      align: 'center',
      maxWidth: 0,
      scale: 1,
      depthMode: 'extrude',
      extrudeDepth: 0.25,
      bevel: 0.15,
      density: 1,
      depthNoise: 0.03,
      waveDepth: 0,
      edgePriority: 0.4,
    },
    particles: {
      count: 20000,
      style: 'soft',
      size: 1.15,
      opacity: 0.4,
      blend: 'additive',
      sizeAttenuation: true,
      depthTest: false,
      softEdge: 0.65,
      glow: 0.22,
      bloom: false,
      bloomStrength: 0.6,
      distanceFade: 0.15,
    },
    motion: {
      enabled: true,
      mode: 'curl',
      strength: 0.12,
      scale: 0.5,
      speed: 0.35,
      damping: 0.9,
      returnForce: 2.4,
      radius: 1.2,
      pointerStrength: 3,
      pointerRepel: false,
      seed: 1337,
    },
    color: {
      mode: 'gradient2',
      color1: '#3a86ff',
      color2: '#ff006e',
      color3: '#8338ec',
      palette: ['#3a86ff', '#ff006e', '#8338ec', '#ffbe0b', '#06d6a0'],
      background: '#050507',
      gradientRotation: 90,
      hueShift: 0,
      saturation: 1,
      brightness: 1,
      contrast: 1,
      animationSpeed: 0,
    },
    morph: {
      duration: 1.8,
      easing: 'easeInOut',
      style: 'direct',
      spring: 3.5,
      damping: 0.82,
      turbulence: 0.15,
      overshoot: 0,
      scatterDistance: 1.5,
      randomDelay: 0.3,
    },
    camera: {
      mode: 'perspective',
      fov: 55,
      autoRotate: false,
      autoRotateSpeed: 0.6,
      damping: 0.08,
      near: 0.01,
      far: 100,
    },
    performance: {
      renderScale: 1,
      // Cap DPR at 1.5: on 4K/5K Retina displays a 2x framebuffer is enormous
      // for additive particles; 1.5 keeps it crisp while roughly halving pixel
      // work. Adaptive quality can still lower render scale under load.
      pixelRatioCap: 1.5,
      adaptiveQuality: true,
      targetFps: 50,
      autoReduce: false,
      paused: false,
    },
  };
}

// Deep clone helper for plain settings objects.
export function clone<T>(v: T): T {
  return JSON.parse(JSON.stringify(v)) as T;
}
